# Generated by Django 4.1 on 2022-08-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_topic_message_room_host_room_participants_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
