# Generated by Django 4.1 on 2022-08-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
